# Generated by Django 5.1.6 on 2025-02-27 12:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_aprovador_drawing_aprobador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='Aprobador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aprovador', to=settings.AUTH_USER_MODEL, verbose_name='Aprobador'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='Status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Ready for review', 'Ready for review'), ('Sent for corrections', 'Sent for corrections'), ('Proposal OK', 'Proposal OK'), ('PLM uploaded', 'PLM uploaded')], default='Not started', max_length=100),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 12, 31, 46, 518422, tzinfo=datetime.timezone.utc), verbose_name='Fecha de emision'),
        ),
    ]
