# Generated by Django 5.1.6 on 2025-02-27 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_drawing_aprobador_alter_drawing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 13, 34, 41, 581354, tzinfo=datetime.timezone.utc), verbose_name='Fecha de emision'),
        ),
    ]
